{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;\f1\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red239\green239\blue239;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c94902\c94902\c94902;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs22\fsmilli11294 \cf0 \cb2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec3 pipeline \{\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 agent any\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 tools \{nodejs "node"\}\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 stages \{\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 stage('Install dependencies') \{\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 steps \{\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 sh 'npm install'\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 \}\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 \}\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 stage('Test') \{\cb1 \strokec0 \

\f1\fs24 \strokec3 \

\f0\fs22\fsmilli11294 \cb2 steps \{\cb1 \strokec0 \

\f1\fs24 \strokec3 \
\cb2 	sh \'91npm test\'92\
\}\
\}\
\}\
\}}